### ISSUE TITLE
[question] Should kernel default cmdline be from linux-loader? 

### ISSUE THREAD

**Issue by gabhijit** [rust-vmm/vmm-reference#80]
A Question: We use a default kernel cmdline if one is not passed as a Config argument. But it seems [linux-loader](https://github.com/rust-vmm/linux-loader/) also has a cmdline. There is a related issue -  https://github.com/rust-vmm/linux-loader/issues/25 . 

Once this is fixed will it be a good idea to actually take a 'default' kernel command line from linux-loader than defining one from this crate?

**Comment by andreeaflorescu** [comment]
> A Question: We use a default kernel cmdline if one is not passed as a Config argument. But it seems [linux-loader](https://github.com/rust-vmm/linux-loader/) also has a cmdline. There is a related issue - [rust-vmm/linux-loader#25](https://github.com/rust-vmm/linux-loader/issues/25) .
> 

We should use the helper functions from `linux-loader`, but there are currently some problems there that we are trying to address. For example, the size of the cmdline is fixed, and once initialized, you cannot add more items to it. Also, the `load_cmdline` function exported by the linux-loader expects a Cstr instead of the `Cmdline` object that the crate defines. These are good issues to fix in linux-loader, and I'll open issues there as well.

We're also already using the helpers from linux-loader, for example when adding the virito device: https://github.com/rust-vmm/vmm-reference/blob/351359bd31ef57017f8b57ed5e0c5ed20e9f27a8/src/devices/src/virtio/block/device.rs#L107

> Once this is fixed will it be a good idea to actually take a 'default' kernel command line from linux-loader than defining one from this crate?

I don't think that linux-loader can provide a default kernel command line that can be used by VMMs. Only the VMM can know what are good  defaults there, because the defaults are tightly coupled with the VMM implementation:
- what devices are implemented?
- does the vmm support PCI, MMIO, or both?
- and many others

These are questions that only the VMM can answer.

Does that make sense?

**Comment by gabhijit** [comment]
> > A Question: We use a default kernel cmdline if one is not passed as a Config argument. But it seems [linux-loader](https://github.com/rust-vmm/linux-loader/) also has a cmdline. There is a related issue - [rust-vmm/linux-loader#25](https://github.com/rust-vmm/linux-loader/issues/25) .
> 
> We should use the helper functions from `linux-loader`, but there are currently some problems there that we are trying to address. For example, the size of the cmdline is fixed, and once initialized, you cannot add more items to it. Also, the `load_cmdline` function exported by the linux-loader expects a Cstr instead of the `Cmdline` object that the crate defines. These are good issues to fix in linux-loader, and I'll open issues there as well.
> 
> We're also already using the helpers from linux-loader, for example when adding the virito device:
> 
> https://github.com/rust-vmm/vmm-reference/blob/351359bd31ef57017f8b57ed5e0c5ed20e9f27a8/src/devices/src/virtio/block/device.rs#L107
> 
> > Once this is fixed will it be a good idea to actually take a 'default' kernel command line from linux-loader than defining one from this crate?
> 
> I don't think that linux-loader can provide a default kernel command line that can be used by VMMs. Only the VMM can know what are good defaults there, because the defaults are tightly coupled with the VMM implementation:
>

Actually, that was a bad way of framing question! :-( What I was trying to say is - have the `cmdline` configured inside linux-loader and then use it here -- something like 

```rust 
linux_loader::get_cmdline().rootfs().into()?;
```
So the last `into` will generate the string, or something like that. 
 
>     * what devices are implemented?
> 
>     * does the vmm support PCI, MMIO, or both?
> 
>     * and many others
> 
> 
> These are questions that only the VMM can answer.
> 
> Does that make sense?

Yes, got it. I saw the same string repeated at two places sometimes so was wondering whether whether it should originate at one place. But this makes sense.

**Comment by andreeaflorescu** [comment]
Right now this is not possible due to limitation to linux-loader (we don't have the functionality implemented to support anything else but virtio configs). Should we close this @gabhijit?

**Comment by gabhijit** [comment]
Yes.. I  was going to close it yesterday, somehow forgot :-) Closing.
